version: '3'
services:
  web:
    build: 
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "5678:5678"
      - "80:80"
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
