"""add_tokens_table

Revision ID: 4fcc87813407
Revises: d874cf677b78
Create Date: 2024-01-21 17:19:08.475409

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.engine.reflection import Inspector

# revision identifiers, used by Alembic.
revision: str = "4fcc87813407"
down_revision: Union[str, None] = "d874cf677b78"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    inspector = Inspector.from_engine(op.get_bind())

    if "tokens" not in inspector.get_table_names():
        op.create_table(
            "tokens",
            sa.Column("id", sa.VARCHAR(length=36), autoincrement=False, nullable=False),
            sa.Column(
                "created_on",
                sa.DateTime(timezone=True),
                server_default=sa.func.current_timestamp(),
            ),
            sa.Column("expires_on", sa.DateTime(timezone=True)),
            sa.Column("user_id", sa.VARCHAR(length=36), sa.ForeignKey("users.id")),
        )


# ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tokens")
    # ### end Alembic commands ###
